---
title: "hw5"
output: github_document
---

```{r setup, include=FALSE}

# Set Up
library(tidyverse)
library(data.table)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
theme_set(theme_bw() + theme(legend.position = "bottom"))
```

# Problem 1
```{r}
# Code Jeff gave us
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

is.list(iris_with_missing)


missing_value = function(x) {
  if (is.numeric(x)) {                    # if the value is numeric 
    y = mean(x, na.rm = TRUE)             # take the mean of the column x and save it as a value y
    x = replace(x, is.na(x), y)           # then replace any missing values in column x with the value y
  } else if (is.character(x)) {           # if the value is character variable
    x = replace(x, is.na(x), "virginica") # replace missing values in column x with virginica
  }
}

# create an output where i map my function onto each variable in my dataframe
output = map_df(iris_with_missing, missing_value)   

# checking to see if my output really works
output 

```

# Problem 2: data

```{r}

# Creating a tibble of data with file names and data

prob_data = tibble(
  subject = list.files(path = "./hw5_data",      # creating a variable "files" for filenames
                     pattern = ".csv$", 
                     full.names = TRUE)) %>%
  mutate(data =  map(subject, read_csv)) %>%    # creating a variable "data" where i read the csv files
  unnest()                                    # unnesting the variable "data"

#tidy the resulting dataset

prob_data =
pivot_longer(prob_data, 
             week_1:week_8,                  # pivoting longer to make each column a variable
             names_to = "week",
              values_to = "observations") %>%
  mutate(subject = str_remove(subject, "./hw5_data/"), # removing the beginning of the subject column
         subject = str_remove(subject, ".csv"),
         subject = str_replace(subject, "con_", "control"),
         subject = str_replace(subject, "exp_", "experimental")) %>% # and removing the beginning of the path of "subject"
  select(subject, week, observations)


knitr::kable(prob_data)
```

# Problem 2: plot

```{r}

# creating a spaghetti plot for the dataframe created above

plot_ppt_data = 
  ggplot(prob_data, aes(x = week, y = observations, color = subject, group = subject)) +
  geom_point() +
  geom_line(aes(color = subject)) +
  viridis::scale_color_viridis(aes(color = subject), discrete = TRUE) +
  labs(
    title = "Participant Observations Over Weeks By Treatment Group",
    x = "Weeks",
    y = "Observation Values"
  )

plot_ppt_data
```

